# Generated by Django 5.0.6 on 2026-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_educator_avatar_educator_bio_educator_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
